apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envConfigMap.name }}
data:
  JDK_JAVA_OPTIONS: -Dspring.config.additional-location=/app/config/application.yaml
  OTEL_SERVICE_NAME: muffin-wallet
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.observability:4317
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_LOGS_EXPORTER: otlp
